name: project
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_localizations:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  http: ^1.2.2
  image_picker: ^1.1.2
  rowbuilder: ^0.0.1
  shared_preferences: ^2.3.3
  string_to_hex: ^0.2.2
  translator: ^1.0.3+1
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/pants.jpg
    - assets/images/avatar.png
    - assets/images/LusoVeste.png
